package easy;

public class FindTheDifference {
	/**
	 * Given two strings s and t which consist of only lower case letters.
	 * String t is generated by random shuffling string s and then add one more letter at a random position.
	 * Find the letter that was added in t.
	 **/
	public static void main(String[] args) {
		System.out.println(findTheDifference("abcd", "abcde"));
		System.out.println(findTheDifference("abcda", "abcdea"));
		System.out.println(findTheDifference("abecda", "abcdeaa"));
	}

	/*
	 * If a character appears in both groups, it must have even number of occurrence.
	 * Return the character with only odd number.
	 */
	public static char findTheDifference(String s, String t) {
		int bits = 0;
		char[] charS = s.toCharArray();
		char[] charT = t.toCharArray();
		for ( int i = 0; i < charS.length; ++i )
			bits = bits ^ ( 1 << ( charS[i] - 'a' ) );
		for ( int i = 0; i < charT.length; ++i )
			bits = bits ^ ( 1 << ( charT[i] - 'a' ) );
		int ans = -1;
		while ( bits != 0 ) {
			++ans;
			bits = bits >> 1;
		}
		return (char) (ans + 'a');
	}
	
	public static char findTheDifferenceCompact(String s, String t) {
		String str = s + t;
		char dif = 0;
		for ( char c : str.toCharArray() ) 
			dif ^= c;
		return dif;
	}
}
